name: Trigger Dev Container Build
on:
  push:
    branches:
      - main

jobs:
  trigger_container_build:
    name: ğŸ‹ Trigger Userspace Container Build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ› ï¸ Trigger BYOB Container Build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ secrets.PAT_USERNAME }}/userspace
          event-type: build_userspace
          client-payload: '{"branch": "main"}'
